// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/probe.proto

package ncapdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Results       []*ProbeResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_probe_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubmitRequest) GetResults() []*ProbeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	TargetHost    string                 `protobuf:"bytes,2,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=at,proto3" json:"at,omitempty"`
	LatencyNs     int64                  `protobuf:"varint,4,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	ThroughputBps float64                `protobuf:"fixed64,5,opt,name=throughput_bps,json=throughputBps,proto3" json:"throughput_bps,omitempty"`
	Detail        string                 `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_proto_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_probe_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProbeResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProbeResult) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *ProbeResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProbeResult) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ProbeResult) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *ProbeResult) GetThroughputBps() float64 {
	if x != nil {
		return x.ThroughputBps
	}
	return 0
}

func (x *ProbeResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_probe_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_probe_proto protoreflect.FileDescriptor

const file_proto_probe_proto_rawDesc = "" +
	"\n" +
	"\x11proto/probe.proto\x12\x05ncapd\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\rSubmitRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\aresults\x18\x02 \x03(\v2\x12.ncapd.ProbeResultR\aresults\"\x8a\x02\n" +
	"\vProbeResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x1f\n" +
	"\vtarget_host\x18\x02 \x01(\tR\n" +
	"targetHost\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x02at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x04 \x01(\x03R\tlatencyNs\x12%\n" +
	"\x0ethroughput_bps\x18\x05 \x01(\x01R\rthroughputBps\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"@\n" +
	"\x0eSubmitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2E\n" +
	"\fProbeService\x125\n" +
	"\x06Submit\x12\x14.ncapd.SubmitRequest\x1a\x15.ncapd.SubmitResponseB,Z*github.com/roberttkach/ncapd/proto;ncapdpbb\x06proto3"

var (
	file_proto_probe_proto_rawDescOnce sync.Once
	file_proto_probe_proto_rawDescData []byte
)

func file_proto_probe_proto_rawDescGZIP() []byte {
	file_proto_probe_proto_rawDescOnce.Do(func() {
		file_proto_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_probe_proto_rawDesc), len(file_proto_probe_proto_rawDesc)))
	})
	return file_proto_probe_proto_rawDescData
}

var file_proto_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_probe_proto_goTypes = []any{
	(*SubmitRequest)(nil),         // 0: ncapd.SubmitRequest
	(*ProbeResult)(nil),           // 1: ncapd.ProbeResult
	(*SubmitResponse)(nil),        // 2: ncapd.SubmitResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_probe_proto_depIdxs = []int32{
	1, // 0: ncapd.SubmitRequest.results:type_name -> ncapd.ProbeResult
	3, // 1: ncapd.ProbeResult.at:type_name -> google.protobuf.Timestamp
	0, // 2: ncapd.ProbeService.Submit:input_type -> ncapd.SubmitRequest
	2, // 3: ncapd.ProbeService.Submit:output_type -> ncapd.SubmitResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_probe_proto_init() }
func file_proto_probe_proto_init() {
	if File_proto_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_probe_proto_rawDesc), len(file_proto_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_probe_proto_goTypes,
		DependencyIndexes: file_proto_probe_proto_depIdxs,
		MessageInfos:      file_proto_probe_proto_msgTypes,
	}.Build()
	File_proto_probe_proto = out.File
	file_proto_probe_proto_goTypes = nil
	file_proto_probe_proto_depIdxs = nil
}
